[project]
name = "transformerimplementation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "spacy>=3.8.7",
    "torch>=2.7.1",
    "torchtext>=0.18.0",
]
